### ISSUE TITLE
Windows sees as a trojan

### ISSUE THREAD

**Issue by ghost** [EsmailELBoBDev2/Folder-Locker#1]
![image](https://user-images.githubusercontent.com/24407938/40124642-a80612e8-5931-11e8-9b9e-22232a1cf832.png)

I've looked in your other projects, and noticed you pack them as .rar. Please don't do that, it gets too much hassle.

You don't need to pack anything you put on GitHub.

**Comment by EsmailELBoBDev2** [comment]
i do that cz my net slow in uploading
